name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: "💥 Breaking Changes"
    label: "breaking"
  - title: "🔥 Removals and Deprecations"
    labels:
      - "removal"
      - "deprecation"
  - title: "🏎️ Performance"
    label: "performance"
  - title: "👷 Continuous Integration"
    labels:
      - "ci"
      - "workflow"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "📦 Dependencies"
    labels:
      - "dependencies"
      - "build"

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION