# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: "4.2.0"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # Prevent giant files from being committed.
    -   id: check-added-large-files
        # check all listed files not just those staged for addition
        args: [--enforce-all]
    # Simply check whether files parse as valid python.
    -   id: check-ast
    # Attempts to load all json files to verify syntax.
    -   id: check-json
    # Attempts to load all TOML files to verify syntax.
    -   id: check-toml
    # Attempts to load all yaml files to verify syntax.
    -   id: check-yaml
    # Check for debugger imports and py37+ breakpoint() calls in python source.
    -   id: debug-statements
    # Checks for the existence of private keys.
    -   id: detect-private-key
    # Makes sure files end in a newline and only a newline.
    -   id: end-of-file-fixer
    # Replaces or checks mixed line ending.
    -   id: mixed-line-ending
    # verifies that test files are named correctly.
    -   id: name-tests-test
        # ensure tests match test_.*\.py
        args: [--pytest-test-first]
    # Protect specific branches from direct checkins.
    # Both main and master are protected by default if no branch argument is set.
    -   id: no-commit-to-branch
    # Checks that all your JSON files are pretty. "Pretty" here means that keys are sorted and indented.
    -   id: pretty-format-json
        # automatically format json files
        args: [--autofix]
    # Sorts entries in requirements.txt and constraints.txt and removes incorrect entry
    -   id: requirements-txt-fixer
    # Trims trailing whitespace.
    -   id: trailing-whitespace

# Hooks which are useful for checking the pre-commit configuration itself.
-   repo: meta
    hooks:
    # Ensures that the configured hooks apply to at least one file in the repository.
    -   id: check-hooks-apply
    # Ensures that exclude directives apply to any file in the repository.
    -   id: check-useless-excludes
