name: "setup-poetry-env"
description: "Composite action to setup Python, Poetry and requirements."

inputs:
  python-version:
    required: false
    description: "The Python version to use"
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: ${{ inputs.python-version }}
        check-latest: true

    - name: Upgrade pip if necessary
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
        pip --version

    - name: Capture Python version
      run: echo "PYTHON_VERSION=$(python --version | awk '{print $2}')" >> "$GITHUB_ENV"

    - name: Install Poetry
      run: |
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} poetry
        pipx inject poetry poetry-plugin-export
        poetry --version

    - name: Install Nox
      run: |
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} nox
        pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
        nox --version
