---
name: CodSpeed

on:
  push: # Run on all Pushes
  pull_request: # Run on all Pull requests
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          install-package: true
          pytest: true
          aiohttp: true
          pytest-asyncio: true
          pytest-codspeed: true

      - name: Run benchmark
        uses: CodSpeedHQ/action@0010eb0ca6e89b80c88e8edaaa07cfe5f3e6664d # v3.5.0
        with:
          run: pytest tests/ --codspeed -rA
          token: ${{ secrets.CODSPEED_TOKEN }}
