name: CodSpeed

on:
    push:
        branches:
            - dev # Run on pushes to dev branch
    pull_request: # Run on all pull requests

jobs:
    codspeed:
        name: Run benchmarks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python 3.13
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.13"
                check-latest: true

            - name: Install dependencies
              run: pip install pytest pytest-codspeed pytest-asyncio

            - name: Run benchmark
              uses: CodSpeedHQ/action@v3.5.0
              with:
                run: pytest tests/ --codspeed -rA
                token: ${{ secrets.CODSPEED_TOKEN }}