name: CodSpeed

on:
    push:
        branches:
            - main
            - dev # Run on pushes to dev branch
            - test
    pull_request: # Run on all pull requests
    # `workflow_dispatch` allows CodSpeed to trigger backtest
    # performance analysis in order to generate initial data.
    workflow_dispatch:

jobs:
    codspeed:
        name: Run benchmarks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python 3.13
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.13"
                check-latest: true

            - name: Upgrade pip if necessary
              run: |
                pip install --constraint=.github/workflows/constraints.txt pip
                pip --version

            - name: Install the package
              run: pip install .

            - name: Install Pytest
              run: |
                pip install --constraint=.github/workflows/constraints.txt pytest
                pytest --version
            
            - name: Install aiohttp
              run: pip install --constraint=.github/workflows/constraints.txt aiohttp
            
            - name: Install asyncio plugin
              run: pip install --constraint=.github/workflows/constraints.txt pytest-asyncio

            - name: Install codspeed plugin
              run: pip install --constraint=.github/workflows/constraints.txt pytest-codspeed

            - name: Run benchmark
              uses: CodSpeedHQ/action@v3.5.0
              with:
                run: pytest tests/ --codspeed -rA
                token: ${{ secrets.CODSPEED_TOKEN }}