---
name: Compatibility and Coverage Tests

on:
  push: # Run on every Push
  pull_request: # Run on every PR

permissions: read-all

jobs:
  compatibility-tests:
    name: Compatibility with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    env:
      NOXSESSION: test_and_coverage
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
          nox: true

      - name: Run Nox
        run: |
          nox -s test-${{ matrix.python-version }}

      - name: Upload coverage data
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-data${{ env.PYTHON_VERSION }}
          path: ".coverage.*"
          include-hidden-files: true
          compression-level: 0

  coverage:
    name: Produce coverage report
    runs-on: ubuntu-latest
    needs: compatibility-tests
    permissions:
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          coverage: true
          nox: true

      - name: Download coverage data
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: coverage-data*

      - name: Move coverage files to root folder
        run: |
          find ~/ -type f -name '.coverage.*' -exec mv -t /home/runner/work/unofficial_tabdeal_api/unofficial_tabdeal_api/ {} +

      - name: Combine coverage data and report
        run: |
          nox -s coverage-3.13

      - name: Upload coverage report To Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          # Disable search for coverage files.
          # This is helpful when specifying what files you want to upload with the files option.
          disable_search: true
          # On error, exit with non-zero code
          fail_ci_if_error: true
          # Comma-separated explicit list of files to upload.
          # These will be added to the coverage files found for upload.
          # If you wish to only upload the specified files, please consider using "disable-search" to disable uploading other files.
          files: ./coverage.xml
          # Use OIDC instead of token. This will ignore any token supplied
          use_oidc: true
          # Enable verbose logging
          verbose: true
