---
name: KICS Scanner

on:
  pull_request: # Run on every pull request
  push: # Run on every Push

permissions: read-all

jobs:
  kics:
    runs-on: ubuntu-latest
    name: kics-action
    permissions:
      pull-requests: write
    steps:
      # Harden the runner (Audit all outbound calls)
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        # Run KICS Scan
      - name: Run KICS Scanner
        uses: checkmarx/kics-github-action@3545b741daf8fc816b081261995184aa12a247c0 # v2.1.11
        with:
          # Enable pull request comments
          enable_comments: true
          # Enable report as jobs summary
          enable_jobs_summary: true
          # Add queries in th pull request report comments
          comments_with_queries: true
          # Disables the exclusion of paths specified within .gitignore file
          exclude_gitignore: true
          # Exclude queries by providing the query ID, comma separated list
          exclude_queries: 555ab8f9-2001-455e-a077-f2d0f41e2fb9,fd54f200-402c-4333-a5a4-36ef6709af2f,b03a748a-542d-44f4-bb86-9199ab4fd2d5
          # Path to the file or directory to scan
          path: '.'
