---
name: KICS Scanner

on:
  pull_request: # Run on every pull request
  push: # Run on every Push

permissions: read-all

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    permissions:
      pull-requests: write
    steps:
      # Harden the runner (Audit all outbound calls)
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        # Run KICS Scan
      - name: Run KICS Scanner
        uses: checkmarx/kics-github-action@c06a133a98c75c2f920014d688015a5fb18095a4 # v2.1.10
        with:
          # Enable pull request comments
          enable_comments: true
          # Enable report as jobs summary
          enable_jobs_summary: true
          # Add queries in th pull request report comments
          comments_with_queries: true
          # Disables the exclusion of paths specified within .gitignore file
          exclude_gitignore: true
          # Exclude queries by providing the query ID, comma separated list
          # exclude_queries: 555ab8f9-2001-455e-a077-f2d0f41e2fb9,fd54f200-402c-4333-a5a4-36ef6709af2f,b03a748a-542d-44f4-bb86-9199ab4fd2d5
          # Path to the file or directory to scan
          path: '.devcontainer/Dockerfile'
