---
name: scan with KICS using config file

on:
  pull_request: # Run on every pull request
  push: # Run on every Push

permissions: read-all

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      # Harden the runner (Audit all outbound calls)
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        # Run KICS Scan
      - name: Run KICS Scan using config
        uses: checkmarx/kics-github-action@c06a133a98c75c2f920014d688015a5fb18095a4 # v2.1.10
        with:
          # Enable pull request comments
          enable_comments: true
          # Enable report as jobs summary
          enable_jobs_summary: true
          # Add queries in th pull request report comments
          comments_with_queries: true
          # D isables the exclusion of paths specified within .gitignore file
          exclude_gitignore: true
          # Path to the file or directory to scan
          path: '.devcontainer/Dockerfile'
