---
name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  push: # Run on every Push
  pull_request:  # Run on every PR

permissions: read-all

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2


      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
        with:
          # Fail the action on broken links
          fail: true
