---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: Run MegaLinter

on:
  push: # Run on every Push
  pull_request: # Run on every PR

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
      # Remove the ones you do not need
      contents: write
      # issues: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter/flavors/documentation@5a91fb06c83d0e69fbd23756d47438aa723b4a5a # v8.7.0
        env:
          # https://megalinter.io/latest/configuration/
          # Disable linters in the listed descriptors
          DISABLE: COPYPASTE
          # Disable specific linters
          DISABLE_LINTERS: BASH_EXEC,BASH_SHFMT,JSON_PRETTIER,SPELL_CSPELL,YAML_PRETTIER,BASH_SHELLCHECK,ACTION_ACTIONLINT,REPOSITORY_GITLEAKS,SPELL_LYCHEE
          # Report results to GitHub status checks
          GITHUB_STATUS_REPORTER: true
          # Python default style to check/apply.
          PYTHON_DEFAULT_STYLE: ruff
          # Displays elapsed time in reports
          SHOW_ELAPSED_TIME: true
          # Validate all files in the codebase, not only modified files
          VALIDATE_ALL_CODEBASE: true
