name: Release package to PyPI

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  release:
    name: Release package to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "{sha}={$(git rev-parse --verify --quiet HEAD^)}" >> "$GITHUB_ENV"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@b1778166f13188a9d478e2d1198f993011ba9864 # v2.0.3
        with:
          version-command: |
            bash -o pipefail -c "poetry version | awk '{ print \$2}'"

      - name: Build package
        run: poetry build --ansi

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4

      - name: Publish the release notes
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          publish: true
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
