name: Tests

on:
    - push
    - pull_request

jobs:
    build-tests:
        name: ${{ matrix.session }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { session: "pre-commit"}
                    - { session: "ruff_check" }
                    - { session: "docs_build" }
                    - { session: "mypy_type" }
                    - { session: "test" }

        env:
            NOXSESSION: ${{ matrix.session }}
            FORCE_COLOR: "1"
            PRE_COMMIT_COLOR: "always"

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python 3.13
              uses: actions/setup-python@v5.5.0
              with:
                python-version: "3.13"
                check-latest: true

            - name: Upgrade pip if necessary
              run: |
                pip install --constraint=.github/workflows/constraints.txt pip
                pip --version

            - name: Capture Python version
              run: echo "PYTHON_VERSION=$(python --version | awk '{print $2}')" >> "$GITHUB_ENV"

            - name: Install Poetry
              run: |
                pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} poetry
                pipx inject poetry poetry-plugin-export
                poetry --version

            - name: Install Nox
              run: |
                pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} nox
                pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
                nox --version

            - name: Run Nox
              run: |
                nox --python=3.13

    compatibility-tests:
      name: Tests for ${{ matrix.python-version }}
      runs-on: ubuntu-latest
      needs: build-tests
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.11", "3.12", "3.13"]

      env:
        NOXSESSION: test_and_coverage
        FORCE_COLOR: "1"
        PRE_COMMIT_COLOR: "always"

      steps:
        - name: Check out the repository
          uses: actions/checkout@v4.2.2

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5.5.0
          with:
            python-version: ${{ matrix.python-version }}
            check-latest: true

        - name: Upgrade pip if necessary
          run: |
            pip install --constraint=.github/workflows/constraints.txt pip
            pip --version

        - name: Capture Python version
          run: echo "PYTHON_VERSION=$(python --version | awk '{print $2}')" >> "$GITHUB_ENV"

        - name: Install Poetry
          run: |
            pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} poetry
            pipx inject poetry poetry-plugin-export
            poetry --version

        - name: Install Nox
          run: |
            pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} nox
            pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
            nox --version

        - name: Run Nox
          run: |
            nox --python=${{ matrix.python-version }}



        - name: Upload coverage data
          uses: actions/upload-artifact@v4.6.2
          with:
            name: coverage-data${{ env.PYTHON_VERSION }}
            path: ".coverage*"
            include-hidden-files: true
