name: Tests

on:
    - push
    - pull_request

jobs:
    build-tests:
        name: ${{ matrix.session }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { session: "pre-commit"}
                    - { session: "ruff_check" }
                    - { session: "docs_build" }
                    - { session: "mypy_type" }
                    - { session: "test" }

        env:
            NOXSESSION: ${{ matrix.session }}
            FORCE_COLOR: "1"
            PRE_COMMIT_COLOR: "always"

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4.2.2

            - name: Set up Python 3.13
              uses: actions/setup-python@v5.5.0
              with:
                python-version: "3.13"
                check-latest: true

            - name: Upgrade pip if necessary
              run: |
                pip install --constraint=.github/workflows/constraints.txt pip
                pip --version

            - name: Capture Python version
              run: echo "PYTHON_VERSION=$(python --version | awk '{print $2}')" >> "$GITHUB_ENV"

            - name: Install Poetry
              run: |
                pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} poetry
                pipx inject poetry poetry-plugin-export
                poetry --version

            - name: Install Nox
              run: |
                pipx install --pip-args=--constraint=.github/workflows/constraints.txt --python ${{ env.PYTHON_VERSION }} nox
                pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry
                nox --version

            - name: Run Nox
              run: |
                nox --python=3.13
